### ISSUE TITLE
registro-login/ desktop

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-06#1]
No encontré la pantalla de  registro-login de desktop

**Comment by Tomasvii** [comment]
Hola Luis! La pantalla de registro-login sería igual tanto en desktop como en móvil, más allá de adaptar los tamaños para cada resolución, lo dimos por sobreentendido.  En respuesta a la pregunta de Discord, serían las dos cosas, tanto productos como servicios lo que ofreceremos. :D

**Comment by Gonssj** [comment]
Hola Luis, tal cual dijo Tomas, si no lo agregamos no hay problema!

**Comment by Gonssj** [comment]
Problema solucionado 👍🏼
