### ISSUE TITLE
Products Router

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-06#7]
https://github.com/1022FSNSANCN02ARED/grupo-06/blob/5141817deb29eca92b7c8243acf2b999b67691ee/src/routers/mainRouter.js#L12

en verdad como estructura capaz mejor si desde el main router salen las dos ramas principales, por ejemplo users y products del resto de las rutas

**Comment by RenzoST** [comment]
implementado👍
