### ISSUE TITLE
Routes 

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-06#8]
https://github.com/1022FSNSANCN02ARED/grupo-06/blob/5141817deb29eca92b7c8243acf2b999b67691ee/src/routers/mainRouter.js#L13-L14

no tiene mucho sentido dos rutas que van al mismo lugar. Para qué les serviría que puedan acceder a un producto desde la ruta /products/:id o catalogue/:id ? parece medio confuso como experiencia de usuario.

**Comment by RenzoST** [comment]
bug solucionado👍
